version: '3.4'

networks:
  coremarketapp:

services:
  appdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 8002:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=password@12345#
    networks:
    - coremarketapp
  webapi:
    container_name: core-market-api
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - 8001:8080
    depends_on:
      - appdb
    environment:
      - DB_HOST=appdb
      - DB_NAME=CoreMarket
      - DB_SA_PASSWORD=password@12345#
    networks:
      - coremarketapp
  